kind: pipeline
name: react-ci-cd

steps:
  - name: echo
    image: node:alpine
    commands:
      - echo 'Run CI / CD Pipeline on Drone'
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm test
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: token
      files: /*
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: webhook
      channel: drone-johann
